# Generated by Django 3.2.13 on 2022-07-01 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
